env:
  matrix:
    - export NODE_VERSION="4" CC=clang-5.0 CXX=clang++-5.0 npm_config_clang=1
    - export NODE_VERSION="6" CC=clang-5.0 CXX=clang++-5.0 npm_config_clang=1
    - export NODE_VERSION="7" CC=clang-5.0 CXX=clang++-5.0 npm_config_clang=1

branches:
#  only:
#    - master

git:
  depth: 10

compiler:
  - clang

addons:
  apt:
    sources:
      - lvm-toolchain-trusty-5.0
    packages:
      - clang-5.0

before_install:
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install

script:
  - npm test
  - cmake .
  - cmake --build .
  - ctest -VV

os:
  - osx
  - linux

dist: trusty
sudo: false
