env:
  matrix:
    - export NODE_VERSION="4"
    - export NODE_VERSION="6"
    - export NODE_VERSION="7"

  include:
    - compiler: gcc
      env: COMPILER=g++-6

    - compiler: clang
      env: COMPILER=clang++-3.9

os:
  - osx
  - linux


branches:
#  only:
#    - master

git:
  depth: 10

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
    packages: ['clang-3.9', 'g++-6']

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install

before_script:
  - env
  - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6" && cmake .;                                 fi
  - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9" npm_config_clang=1 && cmake .;    fi

script:
  - npm test
  - cmake --build .
  - ctest -VV

dist: trusty
sudo: false
